export interface CourseInterface {
  avgRating: number
  reviewsCount: number
  teacher: {
    name: string
    lastName: string
    avatarUrl: string
  }
  description: string
  level: CourseLevel
  id: string
  title: string
  shortDescription: string
  imageUrl: string
  estimatedDuration: number
  categoryId: string
}

export enum CourseLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}

export const courses = {
  data: [
    {
      avgRating: 4.2,
      reviewsCount: 111,
      teacher: {
        name: 'Raúl',
        lastName: 'Rojas',
        avatarUrl: 'https://i.pravatar.cc/150?img=2',
      },
      reviews: [{ rating: 5 }, { rating: 5 }],
      description:
        'Aprende los fundamentos de programación con proyectos reales.',
      level: CourseLevel.BEGINNER,
      id: 'course_001',
      title: 'Introducción a la Programación',
      shortDescription: 'Conceptos base con ejercicios guiados.',
      imageUrl: 'https://picsum.photos/seed/course1/600/400',
      isPublished: true,
      estimatedDuration: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_001',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.1,
      reviewsCount: 159,
      teacher: {
        name: 'Carlos',
        lastName: 'Gonzales',
        avatarUrl: 'https://i.pravatar.cc/150?img=3',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Domina React desde cero hasta nivel profesional.',
      level: CourseLevel.BEGINNER,
      id: 'course_002',
      title: 'React Completo',
      shortDescription: 'Hooks, Context, rendimiento.',
      imageUrl: 'https://picsum.photos/seed/course2/600/400',
      isPublished: true,
      estimatedDuration: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_002',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.5,
      reviewsCount: 43,
      teacher: {
        name: 'Tomás',
        lastName: 'Jiménez',
        avatarUrl: 'https://i.pravatar.cc/150?img=4',
      },
      reviews: [{ rating: 5 }, { rating: 4 }],
      description: 'Crea landing pages modernas con Tailwind CSS.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_003',
      title: 'Tailwind CSS para Principiantes',
      shortDescription: 'Diseño rápido y consistente.',
      imageUrl: 'https://picsum.photos/seed/course3/600/400',
      isPublished: true,
      estimatedDuration: 13,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_003',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.9,
      reviewsCount: 212,
      teacher: {
        name: 'Elena',
        lastName: 'Martínez',
        avatarUrl: 'https://i.pravatar.cc/150?img=5',
      },
      reviews: [{ rating: 3 }, { rating: 4 }],
      description:
        'Curso avanzado para dominar Node.js en entornos productivos.',
      level: CourseLevel.ADVANCED,
      id: 'course_004',
      title: 'Node.js Avanzado',
      shortDescription: 'APIs escalables, clustering, streams.',
      imageUrl: 'https://picsum.photos/seed/course4/600/400',
      isPublished: true,
      estimatedDuration: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_004',
      categoryId: 'data',
    },
    {
      avgRating: 4.5,
      reviewsCount: 62,
      teacher: {
        name: 'Jorge',
        lastName: 'Hernández',
        avatarUrl: 'https://i.pravatar.cc/150?img=6',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Aprende bases sólidas sobre diseño UI moderno.',
      level: CourseLevel.BEGINNER,
      id: 'course_005',
      title: 'Fundamentos de UI Design',
      shortDescription: 'Tipografía, color, layouts.',
      imageUrl: 'https://picsum.photos/seed/course5/600/400',
      isPublished: true,
      estimatedDuration: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_005',
      categoryId: 'data',
    },
    {
      avgRating: 4.7,
      reviewsCount: 356,
      teacher: {
        name: 'Diego',
        lastName: 'Pérez',
        avatarUrl: 'https://i.pravatar.cc/150?img=7',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Curso práctico de bases de datos SQL y modelado.',
      level: CourseLevel.ADVANCED,
      id: 'course_006',
      title: 'SQL y Modelado de Datos',
      shortDescription: 'Consultas, joins, normalización.',
      imageUrl: 'https://picsum.photos/seed/course6/600/400',
      isPublished: true,
      estimatedDuration: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_006',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.7,
      reviewsCount: 80,
      teacher: {
        name: 'Sergio',
        lastName: 'Vargas',
        avatarUrl: 'https://i.pravatar.cc/150?img=8',
      },
      reviews: [{ rating: 3 }, { rating: 4 }],
      description: 'Aprende fundamentos de Python para análisis de datos.',
      level: CourseLevel.BEGINNER,
      id: 'course_007',
      title: 'Python para Data Analysis',
      shortDescription: 'Pandas, Numpy, visualización básica.',
      imageUrl: 'https://picsum.photos/seed/course7/600/400',
      isPublished: true,
      estimatedDuration: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_007',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.3,
      reviewsCount: 229,
      teacher: {
        name: 'Julia',
        lastName: 'Gómez',
        avatarUrl: 'https://i.pravatar.cc/150?img=9',
      },
      reviews: [{ rating: 3 }, { rating: 5 }],
      description: 'Machine learning aplicado con proyectos reales.',
      level: CourseLevel.ADVANCED,
      id: 'course_008',
      title: 'Machine Learning Avanzado',
      shortDescription: 'Algoritmos, pipelines, optimización.',
      imageUrl: 'https://picsum.photos/seed/course8/600/400',
      isPublished: true,
      estimatedDuration: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_008',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.2,
      reviewsCount: 413,
      teacher: {
        name: 'Andrés',
        lastName: 'Navarro',
        avatarUrl: 'https://i.pravatar.cc/150?img=10',
      },
      reviews: [{ rating: 3 }, { rating: 4 }],
      description: 'Aprende Next.js 14 con App Router desde cero.',
      level: CourseLevel.ADVANCED,
      id: 'course_009',
      title: 'Next.js 14 Moderno',
      shortDescription: 'Server components, rutas, optimización.',
      imageUrl: 'https://picsum.photos/seed/course9/600/400',
      isPublished: true,
      estimatedDuration: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_009',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.6,
      reviewsCount: 152,
      teacher: {
        name: 'Alejandro',
        lastName: 'Navarro',
        avatarUrl: 'https://i.pravatar.cc/150?img=11',
      },
      reviews: [{ rating: 4 }, { rating: 3 }],
      description: 'Fundamentos de ciberseguridad para principiantes.',
      level: CourseLevel.ADVANCED,
      id: 'course_010',
      title: 'Ciberseguridad desde Cero',
      shortDescription: 'Amenazas, buenas prácticas, primeros pasos.',
      imageUrl: 'https://picsum.photos/seed/course10/600/400',
      isPublished: true,
      estimatedDuration: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_010',
      categoryId: 'data',
    },
    {
      avgRating: 4.4,
      reviewsCount: 73,
      teacher: {
        name: 'Víctor',
        lastName: 'López',
        avatarUrl: 'https://i.pravatar.cc/150?img=12',
      },
      reviews: [{ rating: 5 }, { rating: 5 }],
      description: 'Desarrolla aplicaciones modernas con Vue.js.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_011',
      title: 'Vue.js desde Cero',
      shortDescription: 'Componentes, Vuex, Vue Router.',
      imageUrl: 'https://picsum.photos/seed/course11/600/400',
      isPublished: true,
      estimatedDuration: 14,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_011',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.4,
      reviewsCount: 369,
      teacher: {
        name: 'Julia',
        lastName: 'Ruiz',
        avatarUrl: 'https://i.pravatar.cc/150?img=13',
      },
      reviews: [{ rating: 3 }, { rating: 4 }],
      description: 'Mejora la experiencia de usuario con técnicas avanzadas.',
      level: CourseLevel.ADVANCED,
      id: 'course_012',
      title: 'Diseño UX Avanzado',
      shortDescription: 'Investigación de usuarios, wireframes.',
      imageUrl: 'https://picsum.photos/seed/course12/600/400',
      isPublished: true,
      estimatedDuration: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_012',
      categoryId: 'diseño',
    },
    {
      avgRating: 4.5,
      reviewsCount: 422,
      teacher: {
        name: 'Raúl',
        lastName: 'Moreno',
        avatarUrl: 'https://i.pravatar.cc/150?img=14',
      },
      reviews: [{ rating: 4 }, { rating: 5 }],
      description: 'Construye aplicaciones enterprise con Angular.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_013',
      title: 'Angular Profesional',
      shortDescription: 'Directivas, services, modules.',
      imageUrl: 'https://picsum.photos/seed/course13/600/400',
      isPublished: true,
      estimatedDuration: 26,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_013',
      categoryId: 'diseño',
    },
    {
      avgRating: 4.5,
      reviewsCount: 86,
      teacher: {
        name: 'Tomás',
        lastName: 'Mendoza',
        avatarUrl: 'https://i.pravatar.cc/150?img=15',
      },
      reviews: [{ rating: 3 }, { rating: 3 }],
      description: 'Domina TypeScript para código más seguro.',
      level: CourseLevel.ADVANCED,
      id: 'course_014',
      title: 'TypeScript Maestro',
      shortDescription: 'Tipos avanzados, generics, decorators.',
      imageUrl: 'https://picsum.photos/seed/course14/600/400',
      isPublished: true,
      estimatedDuration: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_014',
      categoryId: 'data',
    },
    {
      avgRating: 4.3,
      reviewsCount: 345,
      teacher: {
        name: 'Andrés',
        lastName: 'Torres',
        avatarUrl: 'https://i.pravatar.cc/150?img=16',
      },
      reviews: [{ rating: 5 }, { rating: 4 }],
      description: 'Conteneriza y orquesta tus aplicaciones.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_015',
      title: 'Docker y Kubernetes',
      shortDescription: 'Contenedores, orquestación básica.',
      imageUrl: 'https://picsum.photos/seed/course15/600/400',
      isPublished: true,
      estimatedDuration: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_015',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.5,
      reviewsCount: 176,
      teacher: {
        name: 'Sergio',
        lastName: 'Vega',
        avatarUrl: 'https://i.pravatar.cc/150?img=17',
      },
      reviews: [{ rating: 4 }, { rating: 3 }],
      description: 'Implementa APIs GraphQL eficientes.',
      level: CourseLevel.BEGINNER,
      id: 'course_016',
      title: 'GraphQL con Apollo',
      shortDescription: 'Queries, mutations, subscriptions.',
      imageUrl: 'https://picsum.photos/seed/course16/600/400',
      isPublished: true,
      estimatedDuration: 28,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_016',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.0,
      reviewsCount: 409,
      teacher: {
        name: 'Ricardo',
        lastName: 'Jiménez',
        avatarUrl: 'https://i.pravatar.cc/150?img=18',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Aprende Figma desde la perspectiva de un developer.',
      level: CourseLevel.ADVANCED,
      id: 'course_017',
      title: 'Figma para Developers',
      shortDescription: 'Prototipado rápido para devs.',
      imageUrl: 'https://picsum.photos/seed/course17/600/400',
      isPublished: true,
      estimatedDuration: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_017',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.5,
      reviewsCount: 141,
      teacher: {
        name: 'Claudia',
        lastName: 'Navarro',
        avatarUrl: 'https://i.pravatar.cc/150?img=19',
      },
      reviews: [{ rating: 4 }, { rating: 3 }],
      description: 'Analiza datos empresariales con Power BI.',
      level: CourseLevel.BEGINNER,
      id: 'course_018',
      title: 'Power BI para Negocios',
      shortDescription: 'Dashboards, DAX, visualizaciones.',
      imageUrl: 'https://picsum.photos/seed/course18/600/400',
      isPublished: true,
      estimatedDuration: 12,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_018',
      categoryId: 'data',
    },
    {
      avgRating: 4.1,
      reviewsCount: 225,
      teacher: {
        name: 'Fernando',
        lastName: 'Gonzales',
        avatarUrl: 'https://i.pravatar.cc/150?img=20',
      },
      reviews: [{ rating: 3 }, { rating: 3 }],
      description: 'Explora redes neuronales profundas.',
      level: CourseLevel.BEGINNER,
      id: 'course_019',
      title: 'Deep Learning con TensorFlow',
      shortDescription: 'Redes neuronales profundas.',
      imageUrl: 'https://picsum.photos/seed/course19/600/400',
      isPublished: true,
      estimatedDuration: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_019',
      categoryId: 'data',
    },
    {
      avgRating: 4.4,
      reviewsCount: 75,
      teacher: {
        name: 'María',
        lastName: 'Santos',
        avatarUrl: 'https://i.pravatar.cc/150?img=21',
      },
      reviews: [{ rating: 3 }, { rating: 3 }],
      description: 'Automatiza despliegues con DevOps.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_020',
      title: 'DevOps Essentials',
      shortDescription: 'CI/CD, pipelines, monitoring.',
      imageUrl: 'https://picsum.photos/seed/course20/600/400',
      isPublished: true,
      estimatedDuration: 25,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_020',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.8,
      reviewsCount: 256,
      teacher: {
        name: 'Daniela',
        lastName: 'Díaz',
        avatarUrl: 'https://i.pravatar.cc/150?img=22',
      },
      reviews: [{ rating: 5 }, { rating: 5 }],
      description: 'Crea apps móviles cross-platform.',
      level: CourseLevel.ADVANCED,
      id: 'course_021',
      title: 'Flutter para Móviles',
      shortDescription: 'Widgets multiplataforma.',
      imageUrl: 'https://picsum.photos/seed/course21/600/400',
      isPublished: true,
      estimatedDuration: 14,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_021',
      categoryId: 'diseño',
    },
    {
      avgRating: 4.6,
      reviewsCount: 264,
      teacher: {
        name: 'Isabel',
        lastName: 'Ortega',
        avatarUrl: 'https://i.pravatar.cc/150?img=23',
      },
      reviews: [{ rating: 4 }, { rating: 3 }],
      description: 'Mejora el posicionamiento de tus sitios.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_022',
      title: 'SEO y Marketing Digital',
      shortDescription: 'Optimización on-page, analytics.',
      imageUrl: 'https://picsum.photos/seed/course22/600/400',
      isPublished: true,
      estimatedDuration: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_022',
      categoryId: 'data',
    },
    {
      avgRating: 4.0,
      reviewsCount: 323,
      teacher: {
        name: 'María',
        lastName: 'López',
        avatarUrl: 'https://i.pravatar.cc/150?img=24',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Colabora eficientemente con Git.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_023',
      title: 'Git y GitHub Avanzado',
      shortDescription: 'Branching, rebasing, workflows.',
      imageUrl: 'https://picsum.photos/seed/course23/600/400',
      isPublished: true,
      estimatedDuration: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_023',
      categoryId: 'diseño',
    },
    {
      avgRating: 4.1,
      reviewsCount: 74,
      teacher: {
        name: 'Paula',
        lastName: 'Navarro',
        avatarUrl: 'https://i.pravatar.cc/150?img=25',
      },
      reviews: [{ rating: 4 }, { rating: 3 }],
      description: 'Asegura la calidad de tu código.',
      level: CourseLevel.BEGINNER,
      id: 'course_024',
      title: 'Testing con Jest y Cypress',
      shortDescription: 'Unit tests, e2e testing.',
      imageUrl: 'https://picsum.photos/seed/course24/600/400',
      isPublished: true,
      estimatedDuration: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_024',
      categoryId: 'desarrollo',
    },
    {
      avgRating: 4.2,
      reviewsCount: 107,
      teacher: {
        name: 'Sergio',
        lastName: 'Ruiz',
        avatarUrl: 'https://i.pravatar.cc/150?img=26',
      },
      reviews: [{ rating: 5 }, { rating: 4 }],
      description: 'Certifícate en fundamentos de AWS.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_025',
      title: 'AWS Cloud Practitioner',
      shortDescription: 'Servicios AWS esenciales.',
      imageUrl: 'https://picsum.photos/seed/course25/600/400',
      isPublished: true,
      estimatedDuration: 26,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_025',
      categoryId: 'data',
    },
    {
      avgRating: 4.2,
      reviewsCount: 89,
      teacher: {
        name: 'Víctor',
        lastName: 'Martín',
        avatarUrl: 'https://i.pravatar.cc/150?img=27',
      },
      reviews: [{ rating: 4 }, { rating: 4 }],
      description: 'Introducción al mundo blockchain.',
      level: CourseLevel.INTERMEDIATE,
      id: 'course_026',
      title: 'Blockchain y Smart Contracts',
      shortDescription: 'Ethereum, Solidity basics.',
      imageUrl: 'https://picsum.photos/seed/course26/600/400',
      isPublished: true,
      estimatedDuration: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_026',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.7,
      reviewsCount: 384,
      teacher: {
        name: 'Lucía',
        lastName: 'Ferrer',
        avatarUrl: 'https://i.pravatar.cc/150?img=28',
      },
      reviews: [{ rating: 5 }, { rating: 3 }],
      description: 'Diseña gráficos profesionales para web.',
      level: CourseLevel.ADVANCED,
      id: 'course_027',
      title: 'Photoshop para Web Design',
      shortDescription: 'Edición avanzada para web.',
      imageUrl: 'https://picsum.photos/seed/course27/600/400',
      isPublished: true,
      estimatedDuration: 28,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_027',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.7,
      reviewsCount: 95,
      teacher: {
        name: 'Raúl',
        lastName: 'López',
        avatarUrl: 'https://i.pravatar.cc/150?img=29',
      },
      reviews: [{ rating: 3 }, { rating: 3 }],
      description: 'Maneja grandes volúmenes de datos.',
      level: CourseLevel.BEGINNER,
      id: 'course_028',
      title: 'Big Data con Spark',
      shortDescription: 'Procesamiento distribuido.',
      imageUrl: 'https://picsum.photos/seed/course28/600/400',
      isPublished: true,
      estimatedDuration: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_028',
      categoryId: 'negocios',
    },
    {
      avgRating: 4.3,
      reviewsCount: 167,
      teacher: {
        name: 'Pablo',
        lastName: 'Alfaro',
        avatarUrl: 'https://i.pravatar.cc/150?img=30',
      },
      reviews: [{ rating: 4 }, { rating: 5 }],
      description: 'Prepárate para entrevistas técnicas.',
      level: CourseLevel.ADVANCED,
      id: 'course_029',
      title: 'Algoritmos y Estructuras de Datos',
      shortDescription: 'Complejidad, patrones comunes.',
      imageUrl: 'https://picsum.photos/seed/course29/600/400',
      isPublished: true,
      estimatedDuration: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_029',
      categoryId: 'diseño',
    },
    {
      avgRating: 4.8,
      reviewsCount: 87,
      teacher: {
        name: 'Julia',
        lastName: 'Moreno',
        avatarUrl: 'https://i.pravatar.cc/150?img=31',
      },
      reviews: [{ rating: 3 }, { rating: 4 }],
      description: 'Escala aplicaciones con microservicios.',
      level: CourseLevel.BEGINNER,
      id: 'course_030',
      title: 'Microservicios con Spring Boot',
      shortDescription: 'Arquitectura, comunicación.',
      imageUrl: 'https://picsum.photos/seed/course30/600/400',
      isPublished: true,
      estimatedDuration: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
      teacherId: 'teacher_030',
      categoryId: 'desarrollo',
    },
  ],
  total: 30,
  totalPages: 1,
}
